networks:
  microservicios-net:
    driver: bridge

services:
  # --- BASES DE DATOS ---
  db-productos:
    image: mysql
    environment:
      MYSQL_DATABASE: db_productos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db-clientes:
    image: mysql
    environment:
      MYSQL_DATABASE: db_clientes
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db-categorias:
    image: mysql
    environment:
      MYSQL_DATABASE: db_categorias
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db-ventas:
    image: mysql
    environment:
      MYSQL_DATABASE: db_ventas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --- MICROSERVICIOS ---
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - microservicios-net

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - microservicios-net

  productos:
    build: ./productos
    container_name: productos
    depends_on:
      db-productos:
        condition: service_healthy
      eureka:
        condition: service_started
      categorias:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-productos:3306/db_productos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - CATEGORIAS_API_URL=http://categorias:8083/api/v1
    networks:
      - microservicios-net

  clientes:
    build: ./clientes
    container_name: clientes
    depends_on:
      db-clientes:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-clientes:3306/db_clientes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  categorias:
    build: ./categorias
    container_name: categorias
    depends_on:
      db-categorias:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-categorias:3306/db_categorias
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  ventas:
    build: ./ventas
    container_name: ventas
    depends_on:
      db-ventas:
        condition: service_healthy
      eureka:
        condition: service_started
      clientes:
        condition: service_started
      productos:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-ventas:3306/db_ventas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - CLIENTES_API_URL=http://clientes:8081/api/v1
      - PRODUCTOS_API_URL=http://productos:8082/api/v1
    networks:
      - microservicios-net
