server.port=8080
spring.application.name=gateway

# Rutas del gateway
spring.cloud.gateway.routes[0].id=ruta-productos
spring.cloud.gateway.routes[0].uri=lb://PRODUCTOS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/productos/**

spring.cloud.gateway.routes[1].id=ruta-clientes
spring.cloud.gateway.routes[1].uri=lb://CLIENTES
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/clientes/**

spring.cloud.gateway.routes[2].id=ruta-categorias
spring.cloud.gateway.routes[2].uri=lb://CATEGORIAS
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/categorias/**

# Conexión a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/