server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ruta-productos
          uri: lb://PRODUCTOS
          predicates:
            - Path=/api/v1/productos/**

        - id: ruta-clientes
          uri: lb://CLIENTES
          predicates:
            - Path=/api/v1/clientes/**

        - id: ruta-categorias
          uri: lb://CATEGORIAS
          predicates:
            - Path=/api/v1/categorias/**

        - id: ruta-ventas
          uri: lb://VENTAS
          predicates:
            - Path=/api/v1/ventas/**

        - id: productos-api-docs
          uri: lb://PRODUCTOS
          predicates:
            - Path=/v3/api-docs/productos
          filters:
            - RewritePath=/v3/api-docs/productos, /v3/api-docs

        - id: clientes-api-docs
          uri: lb://CLIENTES
          predicates:
            - Path=/v3/api-docs/clientes
          filters:
            - RewritePath=/v3/api-docs/clientes, /v3/api-docs

        - id: categorias-api-docs
          uri: lb://CATEGORIAS
          predicates:
            - Path=/v3/api-docs/categorias
          filters:
            - RewritePath=/v3/api-docs/categorias, /v3/api-docs

        - id: ventas-api-docs
          uri: lb://VENTAS
          predicates:
            - Path=/v3/api-docs/ventas
          filters:
            - RewritePath=/v3/api-docs/ventas, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: productos
        url: /v3/api-docs/productos
      - name: clientes
        url: /v3/api-docs/clientes
      - name: categorias
        url: /v3/api-docs/categorias
      - name: ventas
        url: /v3/api-docs/ventas

logging:
  level:
    root: info
    com.duoc.gateway: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/gateway.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
